=== hornerj94/Verteilte-Systeme/src/main/java/examples/xml/introExamples/syntax/Xml_syntax.dtd
<?xml encoding="UTF-8"?>

<!-- Revision: 1 Xml_syntax.dtd  -->

<!ELEMENT Buecher (Buch|p)+>

<!ELEMENT p (#PCDATA)>

<!ELEMENT Buch (Bestellnummer,Gebiet,Erschienen,Verkaufszahlen,Titel)>
<!ATTLIST Buch Ausgabe (Gebunden|Taschenbuch) "Gebunden">

<!ELEMENT Bestellnummer (#PCDATA)>

<!ELEMENT Gebiet (#PCDATA)>

<!ELEMENT Erschienen (#PCDATA)>

<!ELEMENT Verkaufszahlen (#PCDATA)>

<!ELEMENT Titel (#PCDATA)>

=== hornerj94/Verteilte-Systeme/src/main/java/examples/xml/introExamples/syntax/Xml_syntax.xml
<?xml version="1.0"?>
<!DOCTYPE Buecher SYSTEM "Xml_syntax.dtd" [
<!ENTITY XML "Extensible  Markup Language">
<!ENTITY Taschenbuecher SYSTEM "Taschenbuecher.xml"> ]>

<Buecher>
	<p>Eine Buecherliste aus dem Umfeld der &XML;:</p>
	<Buch Ausgabe="Gebunden">
		<Bestellnummer>13-031</Bestellnummer>
		<Gebiet>HTML</Gebiet>
		<Erschienen>1999-09-06</Erschienen>
		<Verkaufszahlen>12785</Verkaufszahlen>
		<Titel>HTML Grundlagen</Titel>
	</Buch>
   &Taschenbuecher;
	<Buch>
		<Bestellnummer>13-011</Bestellnummer>
		<Gebiet>XML</Gebiet>
		<Erschienen>1999-07-16</Erschienen>
		<Verkaufszahlen>9711</Verkaufszahlen>
		<Titel>XML for Beginners</Titel>
	</Buch>
</Buecher>
